search algorithm, dfs, symmetrical problem

1 2 3
4 5 6
7 8 9

0,0 0,1 0,2
1,0 1,1 1,2
2,0 2,1 2,2

I think implementing this in Lua with a table will be a good idea.

1 -> 2 (right)
  -> 5 (diag)
  -> 4 (down)

the assumption is that we do not know the correct solution.

rules:
you may create straight strikes across the grid until all the numbers have disappeared.

the lower the number of strikes the better. we know it can be done in 4 strikes and 5 strikes.


In [179]:
import numpy as np

class Grid():
    def __init__(self, n, m):
        self.n = n
        self.m = m
        self.pucks = n * m
        self.board = np.int32(511) # there should be a nicer way to express this.
        
    def print_board(self):
        arr = int_to_bits(self.board, 32)
        print(f"{self.board.tobytes()}\n{arr}")
        #arr = str(int_to_bits(myGrid.board, 32))[47:64]
        num = self.board
        for i in range(1,9+1):
            print(int_to_bits(np.right_shift(num, i), 32))

    def available_moves(self):
        pass
        

def int_to_bits(integer, num_bits=None):
    if num_bits is None:
        num_bits = integer.bit_length()
    binary_string = bin(integer)[2:].zfill(num_bits)
    bit_array = np.array([int(bit) for bit in binary_string], dtype=np.int8)
    return bit_array

In [180]:
myGrid = Grid(3,3)

In [181]:
myGrid.print_board()

b'\xff\x01\x00\x00'
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [90]:
myGrid.print_board()

b'\xff\x01\x00\x00'
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1]


In [124]:
str(int_to_bits(myGrid.board, 32))[47:64]

'1 1 1 1 1 1 1 1 1'

In [192]:
print(str(int_to_bits(np.int32(1) << 8 | np.int32(1) << 5 | np.int32(1) << 2,32))[47:64])

1 0 0 1 0 0 1 0 0
